// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FootieData.Vsix
{
    static class Vsix
    {
        public const string Id = "FootieData.Vsix.28693b18-0c2c-4e86-adf2-adce836b749e";
        public const string Name = "FootieData.Vsix";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "";
    }
}
