// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FootieData.Vsix
{
    static class Vsix
    {
        public const string Id = "28693b18-0c2c-4e86-adf2-adce836b749e";
        public const string Name = "VS Sports Desk";
        public const string Description = @"Football league tables in the IDE (2017/18 season)";
        public const string Language = "en-US";
        public const string Version = "1.59";
        public const string Author = "Greg Trevellick";
        public const string Tags = "Bundesliga, Championship, Desk, English, Football, Footie, Footy, League, Liga, Premier, Soccer, Sport, United, Sports, Desk";
    }
}
