// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FootieData.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidToolWindow1PackageString = "4431588e-199d-477f-b3c4-c0b9603602b0";
        public const string guidToolWindow1PackageCmdSetString = "4d2eb9da-e750-4c37-b048-d8a9269e5431";
        public const string guidImagesString = "0be93adf-994a-4383-899b-38cdc03725a2";
        public static Guid guidToolWindow1Package = new Guid(guidToolWindow1PackageString);
        public static Guid guidToolWindow1PackageCmdSet = new Guid(guidToolWindow1PackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
