// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FootieData.Ui
{
    static class Vsix
    {
        public const string Id = "FootieData.Ui.b9ba34c1-b957-4e69-aee6-27ee07b02238";
        public const string Name = "FootieData.Ui";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "";
    }
}
